=== Uniswap/interface/apps/web/public/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://uniswap.org/tokenlist.schema.json",
  "title": "Uniswap Token List",
  "description": "Schema for lists of tokens compatible with the Uniswap Interface",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": [
        "compound",
        "stablecoin"
      ]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of a token extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": [
        "color",
        "is_fee_on_transfer",
        "aliases"
      ]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific token metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#000000",
          "is_verified_by_me": true
        },
        {
          "x-bridged-addresses-by-chain": {
            "1": {
              "bridgeAddress": "0x4200000000000000000000000000000000000010",
              "tokenAddress": "0x4200000000000000000000000000000000000010"
            }
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": [
            "#00000"
          ]
        },
        {
          "type": "boolean",
          "examples": [
            true
          ]
        },
        {
          "type": "number",
          "examples": [
            15
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "name",
        "description"
      ],
      "examples": [
        {
          "name": "Stablecoin",
          "description": "A token with value pegged to another asset"
        }
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this token is deployed",
          "minimum": 1,
          "examples": [
            1,
            42
          ]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [
            18
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": [
            "USD Coin"
          ]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
          "minLength": 1,
          "maxLength": 20,
          "examples": [
            "USDC"
          ]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": [
            "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
          ]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": [
            "stablecoin",
            "compound"
          ]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": [
        "chainId",
        "address",
        "decimals",
        "name",
        "symbol"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 20,
      "pattern": "^[\\w ]+$",
      "examples": [
        "My Token List"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "#/definitions/TokenInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": [
          "compound",
          "lending",
          "personal tokens"
        ]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Stablecoin",
            "description": "A token with value pegged to another asset"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
      ]
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "tokens"
  ]
}

=== Uniswap/interface/src/state/lists/default-pancake-list.json
{
    "name": "PancakeSwap Default List",
    "timestamp": "2022-01-26T11:45:09Z",
    "version": {
      "major": 4,
      "minor": 0,
      "patch": 0
    },
    "tags": {},
    "logoURI": "https://pancakeswap.finance/logo.png",
    "keywords": ["pancake", "default"],
    "tokens": [
      {
        "name": "Wrapped BNB",
        "symbol": "WBNB",
        "address": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png"
      },
      {
        "name": "BUSD Token",
        "symbol": "BUSD",
        "address": "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56.png"
      },
      {
        "name": "Ethereum Token",
        "symbol": "ETH",
        "address": "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x2170Ed0880ac9A755fd29B2688956BD959F933F8.png"
      },
      {
        "name": "BTCB Token",
        "symbol": "BTCB",
        "address": "0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x7130d2A12B9BCbFAe4f2634d864A1Ee1Ce3Ead9c.png"
      },
      {
        "name": "Tether USD",
        "symbol": "USDT",
        "address": "0x55d398326f99059fF775485246999027B3197955",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x55d398326f99059fF775485246999027B3197955.png"
      },
      {
        "name": "PancakeSwap Token",
        "symbol": "CAKE",
        "address": "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82.png"
      },
      {
        "name": "Venus",
        "symbol": "XVS",
        "address": "0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63.png"
      },
      {
        "name": "VAI Stablecoin",
        "symbol": "VAI",
        "address": "0x4BD17003473389A42DAF6a0a729f6Fdb328BbBd7",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x4BD17003473389A42DAF6a0a729f6Fdb328BbBd7.png"
      },
      {
        "name": "Alpaca",
        "symbol": "ALPACA",
        "address": "0x8F0528cE5eF7B51152A59745bEfDD91D97091d2F",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x8F0528cE5eF7B51152A59745bEfDD91D97091d2F.png"
      },
      {
        "name": "Belt",
        "symbol": "BELT",
        "address": "0xE0e514c71282b6f4e823703a39374Cf58dc3eA4f",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xE0e514c71282b6f4e823703a39374Cf58dc3eA4f.png"
      },
      {
        "name": "TokoCrypto",
        "symbol": "TKO",
        "address": "0x9f589e3eabe42ebC94A44727b3f3531C0c877809",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x9f589e3eabe42ebC94A44727b3f3531C0c877809.png"
      },
      {
        "name": "Nerve Finance",
        "symbol": "NRV",
        "address": "0x42F6f551ae042cBe50C739158b4f0CAC0Edb9096",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x42F6f551ae042cBe50C739158b4f0CAC0Edb9096.png"
      },
      {
        "name": "Ellipsis",
        "symbol": "EPS",
        "address": "0xA7f552078dcC247C2684336020c03648500C6d9F",
        "chainId": 56,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xA7f552078dcC247C2684336020c03648500C6d9F.png"
      },
      {
        "name": "PancakeSwap Token",
        "symbol": "CAKE",
        "address": "0xFa60D973F7642B748046464e165A65B7323b0DEE",
        "chainId": 97,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82.png"
      },
      {
        "name": "BUSD Token",
        "symbol": "BUSD",
        "address": "0x8516Fc284AEEaa0374E66037BD2309349FF728eA",
        "chainId": 97,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56.png"
      },
      {
        "name": "BUSD Token",
        "symbol": "BUSD",
        "address": "0x4Fabb145d64652a948d72533023f6E7A623C7C53",
        "chainId": 1,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56.png"
      },
      {
        "name": "BUSD Token",
        "symbol": "BUSD",
        "address": "0x4e2442A6f7AeCE64Ca33d31756B5390860BF973E",
        "chainId": 4,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56.png"
      },
      {
        "name": "Wrapped Ether",
        "address": "0xc778417E063141139Fce010982780140Aa0cD5Ab",
        "symbol": "WETH",
        "decimals": 18,
        "chainId": 4,
        "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xc778417E063141139Fce010982780140Aa0cD5Ab/logo.png"
      },
      {
        "name": "Wrapped Ether",
        "address": "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
        "symbol": "WETH",
        "decimals": 18,
        "chainId": 5,
        "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xc778417E063141139Fce010982780140Aa0cD5Ab/logo.png"
      },
      {
        "name": "Wrapped Ether",
        "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        "symbol": "WETH",
        "decimals": 18,
        "chainId": 1,
        "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png"
      },
      {
        "name": "USD Coin",
        "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "symbol": "USDC",
        "decimals": 6,
        "chainId": 1,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png"
      },
      {
        "name": "Test USD Coin",
        "address": "0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b",
        "symbol": "tUSDC",
        "decimals": 6,
        "chainId": 4,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png"
      },
      {
        "name": "Test USD Coin",
        "address": "0x07865c6E87B9F70255377e024ace6630C1Eaa37F",
        "symbol": "tUSDC",
        "decimals": 6,
        "chainId": 5,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png"
      },
      {
        "name": "Tether USD",
        "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
        "symbol": "USDT",
        "decimals": 6,
        "chainId": 1,
        "logoURI": "https://pancakeswap.finance/images/tokens/0x55d398326f99059fF775485246999027B3197955.png"
      },
      {
        "name": "Wrapped BNB",
        "symbol": "WBNB",
        "address": "0x418D75f65a02b3D53B2418FB8E1fe493759c7605",
        "chainId": 1,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png"
      },
      {
        "name": "Wrapped BNB",
        "symbol": "WBNB",
        "address": "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
        "chainId": 97,
        "decimals": 18,
        "logoURI": "https://pancakeswap.finance/images/tokens/0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c.png"
      }
    ]
  }

=== Uniswap/interface/src/assets/list/swoop-default.tokenlist.json
{
  "name": "Swoop Default List",
  "timestamp": "2020-09-03T20:52:11.844Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "tags": {},
  "logoURI": "https://swoop-exchange.s3-us-west-1.amazonaws.com/swoop.png",
  "keywords": [
    "swoop",
    "default"
  ],
  "tokens": [
    {
      "chainId": 1,
      "address": "0x7a791E76BF4d4f3b9B492AbB74E5108180bE6B5a",
      "symbol": "1LINK",
      "name": "1ChainLink",
      "decimals": 18,
      "logoURI": "https://swoop-exchange.s3-us-west-1.amazonaws.com/tokens/1LINK.png"
    },
    {
      "chainId": 1,
      "address": "0x493c9d4362fB4FD1D0C17a6ECad08de33Fc1d8C2",
      "symbol": "1SEED",
      "name": "1Seed",
      "decimals": 18,
      "logoURI": "https://swoop-exchange.s3-us-west-1.amazonaws.com/tokens/1SEED.png"
    },
    {
      "chainId": 1,
      "address": "0xcBb5B054EC45C69a25c818d6ce02a3c1b9ae6B46",
      "symbol": "HBTC",
      "name": "HBTC",
      "decimals": 18,
      "logoURI": "https://swoop-exchange.s3-us-west-1.amazonaws.com/tokens/HBTC.png"
    },
    {
      "chainId": 1,
      "address": "0xCF1a7272439bEd258311d2034220B63e15d019B1",
      "symbol": "HETH",
      "name": "HETH",
      "decimals": 18,
      "logoURI": "https://swoop-exchange.s3-us-west-1.amazonaws.com/tokens/HETH.png"
    }
  ]
}

=== Uniswap/interface/src/constants/tokenLists/uniswap-v2-unsupported.tokenlist.json
{
  "name": "Uniswap V2 Unsupported List",
  "timestamp": "2021-01-05T20:47:02.923Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "tags": {},
  "logoURI": "ipfs://QmNa8mQkrNKp1WEEeGjFezDmDeodkWRevGFN8JCV7b4Xir",
  "keywords": ["uniswap", "unsupported"],
  "tokens": [

  ]
}

=== Uniswap/interface/src/constants/tokenLists/taiko.tokenlist.json
{
  "name": "Taiko Hoodi Token List",
  "timestamp": "2025-01-24T00:00:00.000Z",
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "tags": {
    "stablecoin": {
      "name": "Stablecoin",
      "description": "Tokens that are fixed to an external asset, e.g. the US dollar"
    },
    "wrapped": {
      "name": "Wrapped",
      "description": "Tokens that represent a wrapped native asset"
    }
  },
  "logoURI": "https://taiko.xyz/images/logos/taiko-icon.svg",
  "keywords": ["taiko", "hoodi", "testnet", "uniswap"],
  "tokens": [
    {
      "name": "Wrapped Ether",
      "address": "0x3B39685B5495359c892DDD1057B5712F49976835",
      "symbol": "WETH",
      "decimals": 18,
      "chainId": 167013,
      "logoURI": "https://tokens.1inch.io/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2.png",
      "tags": ["wrapped"]
    },
    {
      "name": "USD Coin",
      "address": "0x18d5bB147f3D05D5f6c5E60Caf1daeeDBF5155B6",
      "symbol": "USDC",
      "decimals": 6,
      "chainId": 167013,
      "logoURI": "https://tokens.1inch.io/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.png",
      "tags": ["stablecoin"]
    },
    {
      "name": "Tether USD",
      "address": "0xeb4e8Eb83d6FFBa2ce0d8F62ACe60648d1ECE116",
      "symbol": "USDT",
      "decimals": 6,
      "chainId": 167013,
      "logoURI": "https://tokens.1inch.io/0xdac17f958d2ee523a2206206994597c13d831ec7.png",
      "tags": ["stablecoin"]
    }
  ]
}

=== Uniswap/interface/src/constants/tokenLists/goerli.tokenlist.json
{
  "name": "Popular Goerli Tokens",
  "timestamp": "2023-01-18T08:10:26.867Z",
  "version": {
    "major": 0,
    "minor": 1,
    "patch": 0
  },
  "tags": {},
  "logoURI": "ipfs://QmNa8mQkrNKp1WEEeGjFezDmDeodkWRevGFN8JCV7b4Xir",
  "keywords": [
    "test"
  ],
  "tokens": [
    {
      "chainId": 5,
      "address": "0xcc7bb2d219a0fc08033e130629c2b854b7ba9195",
      "name": "Zeta",
      "symbol": "ZETA",
      "decimals": 18,
      "logoURI": "https://assets.coingecko.com/coins/images/18692/large/LOGO1_%287%29.png?1635230502"
    },
    {
      "chainId": 5,
      "address": "0x5a94dc6cc85fda49d8e9a8b85dde8629025c42be",
      "name": "Georli TestNet Bit Token",
      "symbol": "BIT",
      "decimals": 18,
      "logoURI": "https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0x1A4b46696b2bB4794Eb3D4c26f1c55F9170fa4C5/logo.png"
    },
    {
      "chainId": 5,
      "address": "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
      "name": "Wrapped Ether",
      "symbol": "WETH",
      "decimals": 18,
      "logoURI": "https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png"
    },
    {
      "chainId": 5,
      "address": "0x9c556b18d2370d4c44f3b3153d340d9abfd8d995",
      "name": "Wrapped Bitcoin",
      "symbol": "WBTC",
      "decimals": 8,
      "logoURI": "https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599/logo.png"
    },
    {
      "chainId": 5,
      "address": "0x242aa4858284e53d8b657e12a610fb5f03043cfa",
      "name": "Mocked USDT",
      "symbol": "USDT",
      "decimals": 6,
      "logoURI": "https://raw.githubusercontent.com/Uniswap/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png"
    }
  ]
}
